apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
  namespace: devops-genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api
          image: localhost/rag-service:1.0.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: devops-genai-config
            - secretRef:
                name: devops-genai-secrets
          env:
          - name: INFERENCE_ROUTER_URL
            value: "http://inference-router:8000"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: devops-genai-secrets
                key: OPENAI_API_KEY
          - name: OPENAI_MODEL_DEFAULT
            value: "gpt-4o-mini"
          - name: OPENAI_EMBED_MODEL
            value: "text-embedding-3-small"
          - name: CHROMA_DIR
            value: "/data/chroma_db"
          - name: OPENAI_MODEL
            value: "gpt-4o-mini"
          - name: INFERENCE_TIMEOUT_S
            value: "150"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: chroma-data
              mountPath: /data/chroma_db
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-pvc