---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-router
  namespace: devops-genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-router
  template:
    metadata:
      labels:
        app: inference-router
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: inference-router
          image: localhost/inference-router:1.0.14
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-genai-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_MODEL_DEFAULT
              value: "gpt-4o-mini"
            - name: ROUTER_DEFAULT_PROVIDER
              value: "openai"
            - name: ROUTER_ENABLE_FALLBACK
              value: "true"
            - name: ROUTER_FALLBACK_PROVIDER
              value: "mock"
            - name: OLLAMA_BASE_URL
              value: "http://ollama:11434"
            - name: OLLAMA_DEFAULT_MODEL
              value: "llama3.2:1b"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
