"""
Mock Inference Adapter Module

Implements a no-op adapter for testing and development. Returns synthetic responses
without making actual API calls. Useful for integration testing and CI/CD pipelines.
"""
import time
from ..schemas import GenerateRequest, GenerateResponse, Usage


class MockAdapter:
    provider = "mock"

    def generate(self, req: GenerateRequest) -> GenerateResponse:
        model = "mock-fast"

        time.sleep(0.2)

        user_text = ""
        for msg in req.messages:
            if msg.role == "user":
                user_text = msg.content
                break

        output_text = (
            "Summary:\n"
            "- This response was generated by the mock provider.\n\n"
            "Evidence from context:\n"
            "- Mock provider does not perform real model inference.\n\n"
            "Hypotheses (if needed):\n"
            "- None.\n\n"
            "Next data to ingest:\n"
            f"- Original user input was captured as: {user_text[:120]}"
        )

        input_tokens = 80
        output_tokens = 40
        cost_usd = 0.000005

        return GenerateResponse(
            provider=self.provider,
            model_used=model,
            output_text=output_text,
            usage=Usage(
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                cost_usd=cost_usd,
            ),
            latency_ms=200,
        )