import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL_DEFAULT = os.getenv("OPENAI_MODEL_DEFAULT", "gpt-4o-mini")

ROUTER_DEFAULT_PROVIDER = os.getenv("ROUTER_DEFAULT_PROVIDER", "openai")
ROUTER_ENABLE_FALLBACK = os.getenv("ROUTER_ENABLE_FALLBACK", "false").lower() == "true"
ROUTER_FALLBACK_PROVIDER = os.getenv("ROUTER_FALLBACK_PROVIDER", "")