from prometheus_client import Counter, Histogram

INFERENCE_REQUESTS_TOTAL = Counter(
    "inference_requests_total",
    "Total number of inference requests",
    ["provider", "purpose", "model"],
)

INFERENCE_FAILURES_TOTAL = Counter(
    "inference_failures_total",
    "Total number of failed inference requests",
    ["provider", "purpose", "failure_stage"],
)

INFERENCE_LATENCY_SECONDS = Histogram(
    "inference_latency_seconds",
    "Inference latency in seconds",
    ["provider", "purpose", "model"],
    buckets=(0.1, 0.25, 0.5, 1, 2, 5, 10, 20, 30),
)

INFERENCE_INPUT_TOKENS_TOTAL = Counter(
    "inference_input_tokens_total",
    "Total input tokens processed by inference",
    ["provider", "purpose", "model"],
)

INFERENCE_OUTPUT_TOKENS_TOTAL = Counter(
    "inference_output_tokens_total",
    "Total output tokens generated by inference",
    ["provider", "purpose", "model"],
)