-- pgvector bootstrap + operational queries for devops-genai
-- Run with:
--   psql "$PGVECTOR_DSN" -v ON_ERROR_STOP=1 -f deploy/sql/pgvector_bootstrap_and_queries.sql

\set table_name devops_knowledge_chunks
\set embed_dim 1536

BEGIN;

-- Enable the pgvector extension for vector similarity search.
-- This adds the vector data type and distance operators (e.g., <=> for cosine similarity).
-- Required once per database; subsequent runs are idempotent via "IF NOT EXISTS".
CREATE EXTENSION IF NOT EXISTS vector;

-- Create the main knowledge chunks table for storing ingested documents and logs.
-- Column descriptions:
--   id: unique chunk identifier (generated by application, e.g., UUID)
--   doc_id: document batch/ingestion identifier (groups related chunks)
--   source: origin label (e.g., "kb-playbook", "github-actions", "manual")
--   content_type: classification hint ("logs" or "docs") for retrieval filtering
--   chunk_index: sequential position within a document for reconstruction
--   text_content: actual text/log content that is semantically searched
--   embedding: 1536-dimensional vector from OpenAI text-embedding-3-small model
--   repo, pipeline, environment, status, workflow, service_name, run_id: metadata for filtering
--   created_at: timestamp for lifecycle tracking (e.g., cleanup, archival)
CREATE TABLE IF NOT EXISTS :table_name (
    id TEXT PRIMARY KEY,
    doc_id TEXT NOT NULL,
    source TEXT NOT NULL,
    content_type TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    text_content TEXT NOT NULL,
    embedding vector(:embed_dim) NOT NULL,
    repo TEXT,
    pipeline TEXT,
    environment TEXT,
    status TEXT,
    workflow TEXT,
    service_name TEXT,
    run_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create HNSW index on the embedding vector for fast approximate nearest-neighbor search.
-- HNSW (Hierarchical Navigable Small World) is a graph-based approximate index that supports
-- similarity queries in O(log n) time, enabling sub-second retrieval even with millions of chunks.
-- vector_cosine_ops specifies cosine distance as the similarity metric.
CREATE INDEX IF NOT EXISTS idx_devops_knowledge_chunks_embedding_hnsw
ON :table_name USING hnsw (embedding vector_cosine_ops);

-- Create B-tree indexes on metadata columns for efficient filtering during retrieval.
-- These allow queries to filter by source, doc_id, content_type, and run_id before similarity search,
-- reducing the search space and improving query performance.
CREATE INDEX IF NOT EXISTS idx_devops_knowledge_chunks_source ON :table_name (source);
CREATE INDEX IF NOT EXISTS idx_devops_knowledge_chunks_doc_id ON :table_name (doc_id);
CREATE INDEX IF NOT EXISTS idx_devops_knowledge_chunks_content_type ON :table_name (content_type);
CREATE INDEX IF NOT EXISTS idx_devops_knowledge_chunks_run_id ON :table_name (run_id);

-- Commit the transaction.
-- If any command above fails, all changes are rolled back due to atomic transaction semantics.
-- On success, the table and indexes are persistent and ready for ingestion.
COMMIT;

-- ============================================================================
-- Optional: Create application-level role with minimal permissions
-- ============================================================================
-- Use this section to create a dedicated database user for the RAG service.
-- Adjust role name and password according to your organization's database security policy.
-- This isolates the application from administrative operations and enables fine-grained access control.

-- CREATE ROLE app_user WITH LOGIN PASSWORD 'change_me';
-- GRANT USAGE ON SCHEMA public TO app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

-- ============================================================================
-- Operational and Proof Queries
-- (Safe for local/dev environments; selectively enable for production)
-- ============================================================================

-- Query 1: Insert a synthetic test row to validate vector search path.
-- This smoke-test row verifies that embeddings can be stored and HNSW index queries function correctly.
-- Replaces any existing row with id='smoke_1' to stay idempotent on re-runs.
-- Useful for testing after table creation.
INSERT INTO :table_name (
    id, doc_id, source, content_type, chunk_index, text_content, embedding,
    repo, pipeline, environment, status, workflow, service_name, run_id
)
SELECT
    'smoke_1',
    'doc_smoke',
    'kb-playbook',
    'docs',
    0,
    'KB: Restart service after validating config and rollout status.',
    ('[' || string_agg('0.001', ',') || ']')::vector(:embed_dim),
    'demo-repo',
    'deploy',
    'dev',
    'failed',
    'deploy.yml',
    'rag-service',
    'run-smoke-1'
FROM generate_series(1, :embed_dim)
ON CONFLICT (id) DO NOTHING;

-- Query 2: Count total rows in the knowledge chunks table.
-- This returns the total number of ingested chunks stored in pgvector.
-- Use regularly to monitor ingestion volume, growth trends, and storage utilization.
SELECT count(*) AS total_rows FROM :table_name;

-- Query 3: Nearest-neighbor vector similarity search with metadata filtering.
-- This is the core query pattern used by the /ask endpoint for semantic retrieval.
-- It finds the 5 most similar chunks to a query vector (here: a zero vector for testing),
-- filtered by content_type='docs' and source='kb-playbook', ordered by cosine distance.
-- The <=> operator performs cosine similarity search using the HNSW index.
-- Distance 0 = identical vector (most similar); higher distance = less similar.
SELECT
    id,
    source,
    content_type,
    run_id,
    (embedding <=> (SELECT ('[' || string_agg('0.001', ',') || ']')::vector(:embed_dim)
                    FROM generate_series(1, :embed_dim))) AS distance,
    text_content
FROM :table_name
WHERE content_type = 'docs'
  AND source = 'kb-playbook'
ORDER BY embedding <=> (SELECT ('[' || string_agg('0.001', ',') || ']')::vector(:embed_dim)
                        FROM generate_series(1, :embed_dim))
LIMIT 5;

-- Query 4: Aggregate summary of all ingested chunks by source and content type.
-- Use this to audit what data has been ingested, verify distribution across sources (logs vs docs),
-- and ensure no unintended duplicates or missing ingestions. Helpful for operational dashboards and validation.
SELECT source, content_type, count(*) AS chunks
FROM :table_name
GROUP BY source, content_type
ORDER BY source, content_type;

-- Query 5: Delete all chunks from a single source.
-- Use this to remove outdated KB versions, failed log ingestions, or specific data sources
-- without affecting the rest of the knowledge base. Example: reverts an old KB ingestion.
-- Uncomment and adjust the source value as needed.
-- DELETE FROM :table_name WHERE source = 'kb-playbook';

-- Query 6: Full table truncate (equivalent to /reset?confirm=true endpoint).
-- Caution: This permanently removes all chunks without recovery and is intended only for development,
-- testing, or controlled data lifecycle reset. In production, prefer selective deletes by source.
-- Uncomment only when a complete reset is explicitly required.
-- TRUNCATE TABLE :table_name;

/*
**Verify retrieval from KB**
curl -sS -X POST http://localhost:18000/ask \
  -H "Content-Type: application/json" \
  -d '{"question":"What does the KB suggest for app.py missing in CI?","top_k":3,"content_type":"docs","source":"kb-playbook","analysis_mode":"cicd"}'
  
python - <<'PY'
import json, pathlib, urllib.request
text = pathlib.Path("docs/cicd-failure-playbook-kb.md").read_text(encoding="utf-8")
payload = {
"source": "kb-playbook",
"content_type": "docs",
"text": text,
"chunk_size": 1200,
"chunk_overlap": 150
}
req = urllib.request.Request(
"http://localhost:18000/ingest",
data=json.dumps(payload).encode("utf-8"),
headers={"Content-Type": "application/json"},
method="POST",
)
print(urllib.request.urlopen(req, timeout=120).read().decode())
PY

python tools/suggest_fix_executor.py
--agent-url http://localhost:18000
--github-repo <owner/repo>
--github-workflow <workflow-name>
--ingest-logs
--kb-source kb-playbook
--no-create-pr
*/

-- Connect to pgvector
psql "$PGVECTOR_DSN"

-- Then run these queries:

-- Count total chunks
SELECT count(*) FROM devops_knowledge_chunks;

-- Show all sources + chunk breakdown
SELECT source, content_type, count(*) as chunks 
FROM devops_knowledge_chunks 
GROUP BY source, content_type;

-- Show KB chunks with text preview
SELECT id, source, chunk_index, substring(text_content, 1, 100) as preview
FROM devops_knowledge_chunks 
WHERE source = 'kb-playbook' 
LIMIT 10;

-- Show failure logs
SELECT id, source, run_id, substring(text_content, 1, 100) as preview
FROM devops_knowledge_chunks 
WHERE content_type = 'logs' 
LIMIT 10;

-- Vector similarity search (core RAG query)
SELECT 
  id, source, distance,
  substring(text_content, 1, 80) as preview
FROM (
  SELECT 
    id, source,
    (embedding <=> ('[' || string_agg('0.001', ',') || ']')::vector(1536)) as distance,
    text_content
  FROM devops_knowledge_chunks
  WHERE source = 'kb-playbook'
  FROM generate_series(1, 1536)
) t
ORDER BY distance ASC
LIMIT 5;

OR

SELECT 
  id, source, chunk_index,
  substring(text_content, 1, 100) as preview,
  created_at
FROM devops_knowledge_chunks
WHERE source = 'kb-playbook'
LIMIT 10;
-- Inside psql:
\d devops_knowledge_chunks      -- show table schema
SELECT tablename FROM pg_tables WHERE tablename LIKE 'devops%';
SELECT indexname FROM pg_indexes WHERE tablename = 'devops_knowledge_chunks';

psql "$PGVECTOR_DSN" << 'SQL'
SELECT 
  source, 
  content_type, 
  count(*) as chunks,
  max(created_at) as last_ingested
FROM devops_knowledge_chunks
GROUP BY source, content_type
ORDER BY last_ingested DESC;
SQL